import { useState } from 'react'
import { motion } from 'framer-motion'
import { Mail, Phone, MapPin, Send, Clock, Calendar } from 'lucide-react'
import { useLanguage } from '@/contexts/LanguageContext'
import { pick } from '@/lib/i18n'
import type { Language } from '@/lib/translations'
import { toast } from 'sonner'
import horsePortrait from '@/assets/horse-portrait.jpg'

const copy: Record<Language, {
  addr: string; addrP: string; addrS: string; phone: string; phoneS: string; email: string
  hours: string; hoursP: string; hoursS: string
  formTitle: string; namePh: string; subLabel: string; subPh: string
  subs: string[]; msgPh: string
  emTitle: string; emDesc: string; apptTitle: string; apptBullets: string[]
  mapTitle: string; mapLoc: string
}> = {
  de: { addr: 'Adresse', addrP: 'Pferdeklinik Dr. Nolting', addrS: 'Pferdeklinik Straße 12, 30175 Hannover', phone: 'Telefon', phoneS: 'Notfälle 24/7: +49 511 123 4568', email: 'E-Mail', hours: 'Öffnungszeiten', hoursP: 'Mo–Fr: 08:00–18:00', hoursS: 'Sa: 09:00–13:00 (nach Vereinbarung)', formTitle: 'Kontaktformular', namePh: 'Vollständiger Name', subLabel: 'Betreff *', subPh: 'Bitte Betreff wählen', subs: ['Allgemeine Beratung','Lahmheitsuntersuchung','Geplante Operation','Notfall','Zweitmeinung','Nachsorge','Sonstiges'], msgPh: 'Beschreiben Sie Ihr Anliegen…', emTitle: 'Notfälle 24/7', emDesc: 'Bei akuten Notfällen (Kolik, Frakturen, Blutungen) ist unser Team Tag und Nacht erreichbar.', apptTitle: 'Termin vereinbaren', apptBullets: ['Durchschnittliche Wartezeit: 2–3 Werktage','Termine in der Klinik oder mobil','Bitte Krankengeschichte bereithalten','Röntgen und Ultraschall vor Ort verfügbar'], mapTitle: 'Interaktive Karte', mapLoc: 'Hannover, Deutschland' },
  en: { addr: 'Address', addrP: 'Dr. Nolting Equine Clinic', addrS: 'Pferdeklinik Straße 12, 30175 Hanover, Germany', phone: 'Phone', phoneS: 'Emergency 24/7: +49 511 123 4568', email: 'Email', hours: 'Hours', hoursP: 'Mon–Fri: 8:00 AM–6:00 PM', hoursS: 'Sat: 9:00 AM–1:00 PM (by appointment)', formTitle: 'Contact Form', namePh: 'Full name', subLabel: 'Subject *', subPh: 'Select a subject', subs: ['General consultation','Lameness examination','Scheduled surgery','Emergency','Second opinion','Post-op follow-up','Other'], msgPh: 'Describe your request…', emTitle: '24/7 Emergency', emDesc: 'For urgent situations (colic, fractures, bleeding), our team is available day and night.', apptTitle: 'Book an Appointment', apptBullets: ['Average wait: 2–3 business days','On-site or mobile consultations','Have your horse's history ready','X-rays and ultrasound on-site'], mapTitle: 'Interactive map', mapLoc: 'Hanover, Germany' },
  fr: { addr: 'Adresse', addrP: 'Clinique Équine Dr. Nolting', addrS: 'Pferdeklinik Straße 12, 30175 Hanovre, Allemagne', phone: 'Téléphone', phoneS: 'Urgences 24h/24: +49 511 123 4568', email: 'Email', hours: 'Horaires', hoursP: 'Lundi – Vendredi: 8h00 – 18h00', hoursS: 'Samedi: 9h00 – 13h00 (sur RDV)', formTitle: 'Formulaire de Contact', namePh: 'Votre nom complet', subLabel: 'Sujet *', subPh: 'Sélectionnez un sujet', subs: ['Consultation générale','Examen de boiterie','Chirurgie programmée','Urgence','Deuxième avis médical','Suivi post-opératoire','Autre'], msgPh: 'Décrivez votre demande, les symptômes de votre cheval…', emTitle: 'Urgences 24h/24', emDesc: "Pour les situations d'urgence (coliques, fractures, hémorragies), notre équipe est disponible jour et nuit.", apptTitle: 'Prendre Rendez-vous', apptBullets: ['Délai moyen: 2–3 jours ouvrés','Consultations sur place ou en déplacement',"Préparez l'historique médical de votre cheval",'Radiographies et échographies sur place'], mapTitle: 'Carte interactive', mapLoc: 'Hanovre, Allemagne' },
  es: { addr: 'Dirección', addrP: 'Clínica Equina Dr. Nolting', addrS: 'Pferdeklinik Straße 12, 30175 Hannover, Alemania', phone: 'Teléfono', phoneS: 'Urgencias 24/7: +49 511 123 4568', email: 'Correo', hours: 'Horario', hoursP: 'Lun–Vie: 8:00–18:00', hoursS: 'Sáb: 9:00–13:00 (con cita)', formTitle: 'Formulario de contacto', namePh: 'Nombre completo', subLabel: 'Asunto *', subPh: 'Selecciona un asunto', subs: ['Consulta general','Examen de cojera','Cirugía programada','Urgencia','Segunda opinión','Seguimiento postoperatorio','Otro'], msgPh: 'Describe tu solicitud…', emTitle: 'Urgencias 24/7', emDesc: 'Para situaciones urgentes nuestro equipo está disponible día y noche.', apptTitle: 'Pedir cita', apptBullets: ['Tiempo medio: 2–3 días laborables','Consultas en clínica o a domicilio','Ten listo el historial médico','Radiografías y ecografías in situ'], mapTitle: 'Mapa interactivo', mapLoc: 'Hannover, Alemania' },
  pt: { addr: 'Morada', addrP: 'Clínica Equina Dr. Nolting', addrS: 'Pferdeklinik Straße 12, 30175 Hannover, Alemanha', phone: 'Telefone', phoneS: 'Urgências 24/7: +49 511 123 4568', email: 'Email', hours: 'Horário', hoursP: 'Seg–Sex: 08:00–18:00', hoursS: 'Sáb: 09:00–13:00 (com marcação)', formTitle: 'Formulário de contacto', namePh: 'Nome completo', subLabel: 'Assunto *', subPh: 'Selecione um assunto', subs: ['Consulta geral','Exame de claudicação','Cirurgia programada','Urgência','Segunda opinião','Acompanhamento pós-operatório','Outro'], msgPh: 'Descreva o seu pedido…', emTitle: 'Urgências 24/7', emDesc: 'Para situações urgentes a nossa equipa está disponível dia e noite.', apptTitle: 'Marcar consulta', apptBullets: ['Tempo médio: 2–3 dias úteis','Consultas na clínica ou no local','Tenha o histórico médico disponível','Raio-X e ecografia no local'], mapTitle: 'Mapa interativo', mapLoc: 'Hannover, Alemanha' },
  it: { addr: 'Indirizzo', addrP: 'Clinica Equina Dr. Nolting', addrS: 'Pferdeklinik Straße 12, 30175 Hannover, Germania', phone: 'Telefono', phoneS: 'Emergenze 24/7: +49 511 123 4568', email: 'Email', hours: 'Orari', hoursP: 'Lun–Ven: 08:00–18:00', hoursS: 'Sab: 09:00–13:00 (su appuntamento)', formTitle: 'Modulo di contatto', namePh: 'Nome completo', subLabel: 'Oggetto *', subPh: 'Seleziona un oggetto', subs: ['Consulenza generale','Esame della zoppia','Chirurgia programmata','Emergenza','Secondo parere','Follow-up post-operatorio','Altro'], msgPh: 'Descrivi la richiesta…', emTitle: 'Emergenze 24/7', emDesc: 'Per situazioni urgenti il nostro team è disponibile giorno e notte.', apptTitle: 'Prenota un appuntamento', apptBullets: ['Tempo medio: 2–3 giorni lavorativi','Visite in clinica o a domicilio','Tieni pronta la storia clinica','Radiografie ed ecografie in sede'], mapTitle: 'Mappa interattiva', mapLoc: 'Hannover, Germania' },
  no: { addr: 'Adresse', addrP: 'Dr. Nolting Hesteklinikk', addrS: 'Pferdeklinik Straße 12, 30175 Hannover, Tyskland', phone: 'Telefon', phoneS: 'Nødtelefon 24/7: +49 511 123 4568', email: 'E-post', hours: 'Åpningstider', hoursP: 'Man–fre: 08:00–18:00', hoursS: 'Lør: 09:00–13:00 (etter avtale)', formTitle: 'Kontaktskjema', namePh: 'Fullt navn', subLabel: 'Emne *', subPh: 'Velg emne', subs: ['Generell konsultasjon','Haltundersøkelse','Planlagt kirurgi','Nødsituasjon','Second opinion','Oppfølging etter operasjon','Annet'], msgPh: 'Beskriv henvendelsen…', emTitle: 'Nødtelefon 24/7', emDesc: 'Ved akutte situasjoner er teamet tilgjengelig dag og natt.', apptTitle: 'Bestill time', apptBullets: ['Gjennomsnittlig ventetid: 2–3 virkedager','Konsultasjon på klinikk eller ute hos deg','Ha hestens journal tilgjengelig','Røntgen og ultralyd tilgjengelig'], mapTitle: 'Interaktivt kart', mapLoc: 'Hannover, Tyskland' },
  fi: { addr: 'Osoite', addrP: 'Dr. Noltingin hevosklinikka', addrS: 'Pferdeklinik Straße 12, 30175 Hannover, Saksa', phone: 'Puhelin', phoneS: 'Päivystys 24/7: +49 511 123 4568', email: 'Sähköposti', hours: 'Aukioloajat', hoursP: 'Ma–pe: 08:00–18:00', hoursS: 'La: 09:00–13:00 (ajanvarauksella)', formTitle: 'Yhteydenottolomake', namePh: 'Koko nimi', subLabel: 'Aihe *', subPh: 'Valitse aihe', subs: ['Yleinen konsultaatio','Ontumatutkimus','Suunniteltu leikkaus','Hätätilanne','Toinen mielipide','Leikkauksen jälkiseuranta','Muu'], msgPh: 'Kuvaile pyyntösi…', emTitle: 'Päivystys 24/7', emDesc: 'Akuuteissa tilanteissa tiimimme on tavoitettavissa ympäri vuorokauden.', apptTitle: 'Varaa aika', apptBullets: ['Odotusaika: 2–3 arkipäivää','Vastaanotto klinikalla tai paikan päällä','Pidä hevosen sairaushistoria valmiina','Röntgen ja ultraääni saatavilla'], mapTitle: 'Interaktiivinen kartta', mapLoc: 'Hannover, Saksa' },
  sv: { addr: 'Adress', addrP: 'Dr. Noltings Hästklinik', addrS: 'Pferdeklinik Straße 12, 30175 Hannover, Tyskland', phone: 'Telefon', phoneS: 'Akut 24/7: +49 511 123 4568', email: 'E-post', hours: 'Öppettider', hoursP: 'Mån–fre: 08:00–18:00', hoursS: 'Lör: 09:00–13:00 (bokning krävs)', formTitle: 'Kontaktformulär', namePh: 'Fullständigt namn', subLabel: 'Ämne *', subPh: 'Välj ett ämne', subs: ['Allmän konsultation','Hältundersökning','Planerad kirurgi','Akut','Second opinion','Uppföljning efter operation','Annat'], msgPh: 'Beskriv din förfrågan…', emTitle: 'Akut 24/7', emDesc: 'Vid akuta situationer finns vårt team tillgängligt dygnet runt.', apptTitle: 'Boka tid', apptBullets: ['Genomsnittlig väntetid: 2–3 arbetsdagar','Besök på klinik eller på plats','Ha hästens sjukdomshistoria till hands','Röntgen och ultraljud finns på plats'], mapTitle: 'Interaktiv karta', mapLoc: 'Hannover, Tyskland' },
  nl: { addr: 'Adres', addrP: 'Dr. Nolting Paardenkliniek', addrS: 'Pferdeklinik Straße 12, 30175 Hannover, Duitsland', phone: 'Telefoon', phoneS: 'Spoed 24/7: +49 511 123 4568', email: 'E-mail', hours: 'Openingstijden', hoursP: 'Ma–vr: 08:00–18:00', hoursS: 'Za: 09:00–13:00 (op afspraak)', formTitle: 'Contactformulier', namePh: 'Volledige naam', subLabel: 'Onderwerp *', subPh: 'Kies een onderwerp', subs: ['Algemeen consult','Kreupelheidsonderzoek','Geplande operatie','Spoedgeval','Second opinion','Nazorg na operatie','Overig'], msgPh: 'Beschrijf je vraag…', emTitle: 'Spoed 24/7', emDesc: 'Bij urgente situaties is ons team dag en nacht bereikbaar.', apptTitle: 'Afspraak maken', apptBullets: ['Gemiddelde wachttijd: 2–3 werkdagen','Consult op locatie of aan huis','Houd de medische geschiedenis bij de hand','Röntgen en echo beschikbaar op locatie'], mapTitle: 'Interactieve kaart', mapLoc: 'Hannover, Duitsland' },
  ru: { addr: 'Адрес', addrP: 'Конная клиника доктора Нолтинга', addrS: 'Pferdeklinik Straße 12, 30175 Ганновер, Германия', phone: 'Телефон', phoneS: 'Экстренно 24/7: +49 511 123 4568', email: 'Email', hours: 'Часы работы', hoursP: 'Пн–Пт: 08:00–18:00', hoursS: 'Сб: 09:00–13:00 (по записи)', formTitle: 'Форма связи', namePh: 'Полное имя', subLabel: 'Тема *', subPh: 'Выберите тему', subs: ['Общая консультация','Осмотр при хромоте','Плановая операция','Экстренный случай','Второе мнение','Послеоперационный контроль','Другое'], msgPh: 'Опишите ваш запрос…', emTitle: 'Экстренно 24/7', emDesc: 'В срочных ситуациях наша команда доступна круглосуточно.', apptTitle: 'Записаться на приём', apptBullets: ['Среднее ожидание: 2–3 рабочих дня','Приём в клинике или выездной визит','Подготовьте медицинскую историю лошади','Рентген и УЗИ доступны на месте'], mapTitle: 'Интерактивная карта', mapLoc: 'Ганновер, Германия' },
  zh: { addr: '地址', addrP: 'Nolting 医生马科诊所', addrS: 'Pferdeklinik Straße 12, 30175 汉诺威，德国', phone: '电话', phoneS: '24/7 急诊：+49 511 123 4568', email: '邮箱', hours: '营业时间', hoursP: '周一至周五：08:00–18:00', hoursS: '周六：09:00–13:00（需预约）', formTitle: '联系表单', namePh: '姓名', subLabel: '主题 *', subPh: '请选择主题', subs: ['一般咨询','跛行检查','预约手术','急诊','第二意见','术后随访','其他'], msgPh: '请描述您的需求…', emTitle: '24/7 急诊', emDesc: '如遇紧急情况，我们的团队昼夜待命。', apptTitle: '预约就诊', apptBullets: ['平均预约时间：2–3 个工作日','可到院或上门咨询','请准备好马匹病史','现场可进行 X 光与超声'], mapTitle: '交互式地图', mapLoc: '汉诺威，德国' },
  ja: { addr: '住所', addrP: 'ノルティング獣医馬クリニック', addrS: 'Pferdeklinik Straße 12, 30175 ハノーファー', phone: '電話', phoneS: '緊急 24/7：+49 511 123 4568', email: 'メール', hours: '診療時間', hoursP: '月–金：08:00–18:00', hoursS: '土：09:00–13:00（予約制）', formTitle: 'お問い合わせフォーム', namePh: 'お名前', subLabel: '件名 *', subPh: '件名を選択', subs: ['一般相談','跛行検査','予定手術','緊急','セカンドオピニオン','術後フォロー','その他'], msgPh: 'ご相談内容をご記入ください…', emTitle: '緊急 24/7', emDesc: '緊急事態の際は昼夜問わず対応します。', apptTitle: '予約する', apptBullets: ['平均予約取得：2〜3 営業日','院内または出張診察','病歴資料をご用意ください','X線・超音波検査が院内で可能'], mapTitle: 'マップ', mapLoc: 'ハノーファー（ドイツ）' },
  ar: { addr: 'العنوان', addrP: 'عيادة الخيول د. نولتينغ', addrS: 'Pferdeklinik Straße 12, 30175 هانوفر، ألمانيا', phone: 'الهاتف', phoneS: 'الطوارئ 24/7: +49 511 123 4568', email: 'البريد الإلكتروني', hours: 'ساعات العمل', hoursP: 'الاثنين – الجمعة: 08:00 – 18:00', hoursS: 'السبت: 09:00 – 13:00 (بموعد)', formTitle: 'نموذج التواصل', namePh: 'الاسم الكامل', subLabel: 'الموضوع *', subPh: 'اختر موضوعاً', subs: ['استشارة عامة','فحص العرج','جراحة مجدولة','طارئ','رأي ثانٍ','متابعة بعد العملية','أخرى'], msgPh: 'صف طلبك…', emTitle: 'طوارئ 24/7', emDesc: 'للحالات العاجلة فريقنا متاح ليلاً ونهاراً.', apptTitle: 'حجز موعد', apptBullets: ['متوسط مدة الحجز: 2–3 أيام عمل','استشارات في العيادة أو في الموقع','حضّر السجل الطبي للحصان','أشعة وموجات فوق صوتية متوفرة'], mapTitle: 'خريطة تفاعلية', mapLoc: 'هانوفر، ألمانيا' },
}

export function Contact() {
  const { t, language } = useLanguage()
  const c = pick(language, copy)
  const [formData, setFormData] = useState({ name: '', email: '', phone: '', subject: '', message: '' })
  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); toast.success(t('contactSuccess')); setFormData({ name: '', email: '', phone: '', subject: '', message: '' }) }
  const contactInfo = [
    { icon: MapPin, title: c.addr, primary: c.addrP, secondary: c.addrS },
    { icon: Phone, title: c.phone, primary: '+49 511 123 4567', secondary: c.phoneS },
    { icon: Mail, title: c.email, primary: 'contact@dr-nolting.com', secondary: 'urgences@dr-nolting.com' },
    { icon: Clock, title: c.hours, primary: c.hoursP, secondary: c.hoursS },
  ]

  return (
    <section id="contact" className="relative py-24 bg-background overflow-hidden">
      <div className="absolute inset-0 opacity-5"><img src={horsePortrait} alt="" className="w-full h-full object-cover" /></div>
      <div className="container mx-auto px-6 sm:px-8 lg:px-12 relative z-10">
        <div className="text-center mb-16">
          <span className="inline-block px-4 py-2 bg-accent/10 text-accent rounded-full text-sm font-medium mb-6 border border-accent/20">{t('contactTag')}</span>
          <h1 className="font-display text-4xl sm:text-5xl font-bold text-foreground mb-6">{t('contactTitle')}</h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">{t('contactSubtitle')}</p>
        </div>
        <div className="grid md:grid-cols-4 gap-6 mb-16">
          {contactInfo.map((info, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }} viewport={{ once: true }} className="p-6 bg-card/80 backdrop-blur-sm rounded-2xl border border-border text-center">
              <div className="w-12 h-12 bg-accent/10 rounded-xl flex items-center justify-center mx-auto mb-4"><info.icon className="w-6 h-6 text-accent" /></div>
              <h4 className="font-display font-bold text-foreground mb-2">{info.title}</h4>
              <p className="text-foreground text-sm mb-1">{info.primary}</p>
              <p className="text-muted-foreground text-xs">{info.secondary}</p>
            </motion.div>
          ))}
        </div>
        <div className="grid lg:grid-cols-2 gap-12 max-w-6xl mx-auto">
          <motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="bg-card/80 backdrop-blur-sm p-8 rounded-2xl border border-border">
            <h3 className="font-display text-2xl font-bold text-foreground mb-6">{c.formTitle}</h3>
            <form onSubmit={handleSubmit} className="space-y-5">
              <div className="grid md:grid-cols-2 gap-5">
                <div><label className="block text-sm font-medium text-foreground mb-2">{t('contactName')} *</label><input type="text" required value={formData.name} onChange={(e) => setFormData({ ...formData, name: e.target.value })} className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:ring-2 focus:ring-accent focus:border-transparent transition-all" placeholder={c.namePh} /></div>
                <div><label className="block text-sm font-medium text-foreground mb-2">{t('contactEmail')} *</label><input type="email" required value={formData.email} onChange={(e) => setFormData({ ...formData, email: e.target.value })} className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:ring-2 focus:ring-accent focus:border-transparent transition-all" placeholder="email@example.com" /></div>
              </div>
              <div className="grid md:grid-cols-2 gap-5">
                <div><label className="block text-sm font-medium text-foreground mb-2">{t('contactPhone')}</label><input type="tel" value={formData.phone} onChange={(e) => setFormData({ ...formData, phone: e.target.value })} className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:ring-2 focus:ring-accent focus:border-transparent transition-all" placeholder="+49 XXX XXXXXXX" /></div>
                <div><label className="block text-sm font-medium text-foreground mb-2">{c.subLabel}</label><select required value={formData.subject} onChange={(e) => setFormData({ ...formData, subject: e.target.value })} className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:ring-2 focus:ring-accent focus:border-transparent transition-all"><option value="">{c.subPh}</option>{c.subs.map(s => <option key={s} value={s}>{s}</option>)}</select></div>
              </div>
              <div><label className="block text-sm font-medium text-foreground mb-2">{t('contactMessage')} *</label><textarea required rows={5} value={formData.message} onChange={(e) => setFormData({ ...formData, message: e.target.value })} className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:ring-2 focus:ring-accent focus:border-transparent resize-none transition-all" placeholder={c.msgPh} /></div>
              <button type="submit" className="w-full gold-accent font-semibold px-6 py-4 rounded-lg flex items-center justify-center gap-2 hover:scale-[1.02] transition-transform"><Send className="w-5 h-5" />{t('contactSend')}</button>
            </form>
          </motion.div>
          <motion.div initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="space-y-8">
            <div className="p-6 bg-accent/10 rounded-2xl border border-accent/30">
              <div className="flex items-center gap-4 mb-4"><div className="w-12 h-12 bg-accent rounded-xl flex items-center justify-center"><Phone className="w-6 h-6 text-primary-foreground" /></div><div><h4 className="font-display font-bold text-foreground">{c.emTitle}</h4><p className="text-accent font-bold text-lg">+49 511 123 4568</p></div></div>
              <p className="text-muted-foreground text-sm">{c.emDesc}</p>
            </div>
            <div className="p-6 bg-card/80 backdrop-blur-sm rounded-2xl border border-border">
              <div className="flex items-center gap-4 mb-4"><div className="w-12 h-12 bg-accent/10 rounded-xl flex items-center justify-center"><Calendar className="w-6 h-6 text-accent" /></div><h4 className="font-display font-bold text-foreground">{c.apptTitle}</h4></div>
              <ul className="space-y-3 text-muted-foreground">{c.apptBullets.map((b, i) => (<li key={i} className="flex items-start gap-2"><span className="w-2 h-2 bg-accent rounded-full mt-2 flex-shrink-0" />{b}</li>))}</ul>
            </div>
            <div className="rounded-2xl overflow-hidden border border-border h-48 bg-card flex items-center justify-center"><div className="text-center"><MapPin className="w-12 h-12 text-accent/30 mx-auto mb-2" /><p className="text-muted-foreground">{c.mapTitle}</p><p className="text-sm text-muted-foreground">{c.mapLoc}</p></div></div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
